# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql.yaml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rgilles <rgilles@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/19 04:01:30 by rgilles           #+#    #+#              #
#    Updated: 2021/03/19 04:01:32 by rgilles          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: influxdb
  name: influxdb-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: influxdb
  template: 
    metadata: 
      labels: 
        app: influxdb
    spec: 
      containers:
      - name: influxdb
        env:
        - name: DB_USER
          valueFrom: 
            secretKeyRef:
              key: user
              name: influxdb-secret
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef: 
              key: password
              name: influxdb-secret
        - name: DB_ROOTPASSWORD
          valueFrom: 
            secretKeyRef: 
              key: root-password
              name: influxdb-secret
        image: influxdb
        imagePullPolicy: Never
        volumeMounts:
        - name: influxdb-storage
          mountPath: /root/.influxdb
        ports: 
        - containerPort: 8086
      volumes:
      - name: influxdb-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
    name: influxdb-entrypoint
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
  - port: 8086
    targetPort: 8086
