# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql.yaml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rgilles <rgilles@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/19 04:01:30 by rgilles           #+#    #+#              #
#    Updated: 2021/03/19 04:01:32 by rgilles          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mysql
  name: mysql-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mysql
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers:
      - name: mysql
        env:
        - name: DB_USER
          valueFrom: 
            secretKeyRef:
              key: user
              name: wp-secret
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef: 
              key: password
              name: wp-secret
        - name: DB_ROOTPASSWORD
          valueFrom: 
            secretKeyRef: 
              key: root-password
              name: wp-secret
        image: mysql
        imagePullPolicy: Never
        ports: 
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
    name: mysql-entrypoint
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
