# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    secret.yaml                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rgilles <rgilles@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/18 16:02:23 by rgilles           #+#    #+#              #
#    Updated: 2021/03/18 16:02:25 by rgilles          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
type: Opaque
stringData:
  user: admin
  password: admin
  root-password: password
