{
 "title": "Dashboard Global",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU - Wordpress",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "CPU - PhpMyAdmin",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "phpmyadmin" }
     ]
    }
   ]
  },
  {
   "title": "CPU - Nginx",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 0 },
   "content": "<div style=\"text-align:center; font-size:30px;\" >Nb Process</div>",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "wordpress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "phpmyadmin",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "phpmyadmin" }
     ]
    }
   ]
  },
  {
   "title": "nginx",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  },
  {
   "title": "CPU - Mysql",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mysql" }
     ]
    }
   ]
  },
  {
   "title": "CPU - Grafana",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "grafana" }
     ]
    }
   ]
  },
  {
   "title": "CPU - FTPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ftps" }
     ]
    }
   ]
  },
  {
   "title": "mysql",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mysql" }
     ]
    }
   ]
  },
  {
   "title": "grafana",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "grafana" }
     ]
    }
   ]
  },
  {
   "title": "ftps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ftps" }
     ]
    }
   ]
  },
  {
   "title": "CPU - InfluxDB",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "influxdb",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "memory (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "global cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "cpu usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}