# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx.yaml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rgilles <rgilles@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/07 12:21:47 by rgilles           #+#    #+#              #
#    Updated: 2021/03/07 12:21:49 by rgilles          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: nginx
  name: nginx
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata:
      labels: 
        app: nginx
    spec: 
      containers:
      - name: nginx
        env:
        - name: IDB_HOST
          value: influxdb-entrypoint.default.svc.cluster.local
        - name: IDB_USER
          valueFrom: 
            secretKeyRef:
              key: user
              name: influxdb-secret
        - name: IDB_PASSWORD
          valueFrom: 
            secretKeyRef: 
              key: password
              name: influxdb-secret
        image: nginx
        imagePullPolicy: Never
        ports: 
        - containerPort: 80
        - containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
    name: nginx-entrypoint
    annotations:
      metallb.universe.tf/allow-shared-ip: entrypoint
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
