# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    wordpress.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rgilles <rgilles@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/07 12:21:47 by rgilles           #+#    #+#              #
#    Updated: 2021/03/07 12:21:49 by rgilles          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: wordpress
  name: wordpress-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: wordpress
  template: 
    metadata: 
      labels: 
        app: wordpress
    spec: 
      containers:
      - name: wordpress 
        env: 
        - name: DB_NAME
          value: wordpress
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          valueFrom: 
            secretKeyRef:
              key: user
              name: wp-secret
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef: 
              key: password
              name: wp-secret
        image: wordpress
        imagePullPolicy: Never
        ports: 
        - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
    name: wordpress-entrypoint
    annotations:
      metallb.universe.tf/allow-shared-ip: entrypoint
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
