# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    wordpress.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rgilles <rgilles@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/07 12:21:47 by rgilles           #+#    #+#              #
#    Updated: 2021/03/07 12:21:49 by rgilles          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: ftps
  name: ftps
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: ftps
  template: 
    metadata:
      labels: 
        app: ftps
    spec: 
      containers:
      - name: ftps
        env:
        - name: IDB_HOST
          value: influxdb-entrypoint.default.svc.cluster.local
        - name: IDB_USER
          valueFrom: 
            secretKeyRef:
              key: user
              name: influxdb-secret
        - name: IDB_PASSWORD
          valueFrom: 
            secretKeyRef: 
              key: password
              name: influxdb-secret
        image: ftps
        imagePullPolicy: Never
        ports: 
        - containerPort: 21
        - containerPort: 20
        - containerPort: 8975

---
apiVersion: v1
kind: Service
metadata:
    name: ftps-entrypoint
    annotations:
      metallb.universe.tf/allow-shared-ip: entrypoint
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
    name: auth
  - port: 20
    targetPort: 20
    name: data
  - port: 8975
    targetPort: 8975
    name: passv
